"""empty message

Revision ID: 238fcebd8f1b
Revises: 3d06cb27a618
Create Date: 2025-06-20 22:12:35.157831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238fcebd8f1b'
down_revision: Union[str, None] = '3d06cb27a618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
